"""parametres de variation des recettes de mobilier

Le moteur de rendu sait déjà traduire un `variant_params` d'instance en répétitions
(`app/geometry/furniture.py::resolve_variants`), mais il lit pour cela la déclaration portée par
la recette — et la table n'avait pas de colonne où la ranger. Sans elle, le nombre de tiroirs ou
d'étagères choisi sur un meuble restait sans aucun effet.

Colonne seule, NOT NULL avec `server_default '[]'` : les recettes déjà semées deviennent des
recettes sans paramètre de variation, ce qui est exactement leur comportement actuel.

Revision ID: 75eba53422d6
Revises: a4f61c0d3b7e
Create Date: 2026-08-08 00:16:06.034664
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = '75eba53422d6'
down_revision: str | None = 'a4f61c0d3b7e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('furnituretype', sa.Column('variants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('furnituretype', 'variants')
    # ### end Alembic commands ###
