"""modele de donnees initial

Revision ID: 8de2811b136b
Revises: 
Create Date: 2026-08-02 18:31:38.080089
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = '8de2811b136b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('furnituretype',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color_slots', sa.JSON(), nullable=False),
    sa.Column('parts', sa.JSON(), nullable=False),
    sa.Column('default_width_cm', sa.Float(), nullable=False),
    sa.Column('default_height_cm', sa.Float(), nullable=False),
    sa.Column('default_depth_cm', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_furnituretype_category'), 'furnituretype', ['category'], unique=False)
    op.create_index(op.f('ix_furnituretype_slug'), 'furnituretype', ['slug'], unique=True)
    op.create_table('project',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_table('room',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('wall_thickness_cm', sa.Float(), nullable=False),
    sa.Column('ceiling_height_cm', sa.Float(), nullable=False),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_project_id'), 'room', ['project_id'], unique=False)
    op.create_table('sharedview',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharedview_project_id'), 'sharedview', ['project_id'], unique=False)
    op.create_index(op.f('ix_sharedview_token'), 'sharedview', ['token'], unique=True)
    op.create_table('face',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('kind', sa.Enum('WALL', 'FLOOR', 'CEILING', name='facekind'), nullable=False),
    sa.Column('start_x_cm', sa.Float(), nullable=True),
    sa.Column('start_y_cm', sa.Float(), nullable=True),
    sa.Column('end_x_cm', sa.Float(), nullable=True),
    sa.Column('end_y_cm', sa.Float(), nullable=True),
    sa.Column('covering', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'label', name='uq_face_room_label')
    )
    op.create_index(op.f('ix_face_room_id'), 'face', ['room_id'], unique=False)
    op.create_table('element',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('face_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('DOOR_HINGED', 'DOOR_SLIDING', 'WINDOW', 'FURNITURE', name='elementkind'), nullable=False),
    sa.Column('x_offset_cm', sa.Float(), nullable=False),
    sa.Column('y_offset_cm', sa.Float(), nullable=False),
    sa.Column('width_cm', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('depth_cm', sa.Float(), nullable=False),
    sa.Column('rotation_deg', sa.Float(), nullable=False),
    sa.Column('furniture_type_id', sa.Integer(), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('variant_params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['face_id'], ['face.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['furniture_type_id'], ['furnituretype.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_element_face_id'), 'element', ['face_id'], unique=False)
    op.create_index(op.f('ix_element_furniture_type_id'), 'element', ['furniture_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_element_furniture_type_id'), table_name='element')
    op.drop_index(op.f('ix_element_face_id'), table_name='element')
    op.drop_table('element')
    op.drop_index(op.f('ix_face_room_id'), table_name='face')
    op.drop_table('face')
    op.drop_index(op.f('ix_sharedview_token'), table_name='sharedview')
    op.drop_index(op.f('ix_sharedview_project_id'), table_name='sharedview')
    op.drop_table('sharedview')
    op.drop_index(op.f('ix_room_project_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_furnituretype_slug'), table_name='furnituretype')
    op.drop_index(op.f('ix_furnituretype_category'), table_name='furnituretype')
    op.drop_table('furnituretype')
    # ### end Alembic commands ###
