"""index composite pour la liste des projets

Revision ID: b0401c711d34
Revises: c2a9d1f47d84
Create Date: 2026-08-02 20:02:56.330385
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op



revision: str = 'b0401c711d34'
down_revision: str | None = 'c2a9d1f47d84'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_project_owner_updated', 'project', ['owner_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_owner_updated', table_name='project')
    # ### end Alembic commands ###
